import { defineType, defineField } from 'sanity'
import { orderRankField, orderRankOrdering } from '@sanity/orderable-document-list'

// One gallery card. Media now lives natively in Sanity (no ImageKit):
//   image        — for image cards (Sanity transforms it on delivery)
//   video        — for video cards (full compressed file, served as-is)
//   videoPreview — 3s grid clip, auto-generated by the sync-previews Action
// Editors upload ONE file — into `image` or `video` — directly in the Studio.
export const mediaItem = defineType({
  name: 'mediaItem',
  title: 'Media item',
  type: 'document',
  orderings: [orderRankOrdering],
  fields: [
    orderRankField({ type: 'mediaItem' }),
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      validation: (rule) => rule.required(),
    }),
    defineField({ name: 'description', title: 'Description', type: 'text', rows: 3 }),
    defineField({
      name: 'alt',
      title: 'Alt text',
      type: 'string',
      description: 'Short accessibility description (mainly for images).',
    }),
    defineField({
      name: 'tags',
      title: 'Tags',
      type: 'array',
      of: [{ type: 'string' }],
      options: {
        list: [
          { title: 'interface', value: 'interface' },
          { title: 'motion', value: 'motion' },
          { title: 'graphic', value: 'graphic' },
        ],
      },
    }),
    defineField({
      name: 'image',
      title: 'Image',
      type: 'image',
      options: { hotspot: true },
      description: 'Upload here for an image card.',
    }),
    defineField({
      name: 'video',
      title: 'Video',
      type: 'file',
      options: { accept: 'video/*' },
      description: 'Upload here for a video card (the full clip).',
    }),
    defineField({
      name: 'videoPreview',
      title: 'Video grid preview',
      type: 'file',
      options: { accept: 'video/*' },
      readOnly: true,
      description: 'Auto-generated 3s clip for the grid. Do not edit.',
    }),
  ],
  // Exactly one of image / video.
  validation: (rule) =>
    rule.custom((doc) => {
      const hasImage = Boolean(doc?.image?.asset)
      const hasVideo = Boolean(doc?.video?.asset)
      if (hasImage === hasVideo) return 'Add exactly one: an image OR a video.'
      return true
    }),
  preview: {
    select: { title: 'title', image: 'image', video: 'video.asset.originalFilename' },
    prepare({ title, image, video }) {
      return {
        title: title || '(untitled)',
        subtitle: image ? 'image' : video ? `video · ${video}` : '(no media)',
        media: image || undefined,
      }
    },
  },
})
